config/routes.rb
Basement::Application.routes.draw do
  get '/sitemap.xml' => 'admin#sitemap', defaults: {format: :xml}
  get '/admin/reset_cache' => 'admin#reset_cache'
  get '/me.vcard' => 'interest#vcard', as: :vcard

  Helper::menu.each do |item|
    get "/#{item.id}"  => "#{item.id}#index"
    item.subitems.each do |subitem|
      get "/#{item.id}/#{subitem.id}"  => "#{item.id}##{subitem.id}"
    end
  end

  root to: 'home#index'
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_action :prepare_cache

  def sitemap
    response.headers["Content-Type"] = 'text/xml'
    render layout: false
  end

  def reset_cache
    render plain: "reset redis cache: #{Rails.cache.clear}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  before_action :prepare_cache

  # prepare all the caching and loading-stuff for each request
  def prepare_cache
    @rendering_start = Time.new
    cache_and_set(:tweets)        { Helper::twitter_posts }
    cache_and_set(:friends)       { Helper::twitter_friends }
    cache_and_set(:fotos)         { Helper::picasa_fotos }
    cache_and_set(:posts)         { Helper::blogger_posts }
    cache_and_set(:books)         { Helper::load_data(:books).shuffle.first(20) }
    cache_and_set(:repos)         { Helper::repos }
    cache_and_set(:gists)         { Helper::gists }

    @cites = Helper::load_data(:cites).shuffle
    @teaser = [:blog, :bookshelf, :gallery, :twitter, :repos, :gists]
    2.times.each{@teaser.delete_at(rand(@teaser.size))}
  end

  # extend render-method to not render a layout for xhr requests
  def render(*args)
    args << {:layout=>false} if request.xhr? and args.empty?
    args.first[:layout] = false if request.xhr? and args.first[:layout].nil?
    super
  end

  private

  # generic helper for adding more results to view
  def more_stuff(size, initial_count=3)
    unless params[:id].nil?
      session[action_name] = params[:id].to_i
      session[action_name] = (size - 1) if session[action_name] >= size
    end
    count = session[action_name] ||= initial_count
    @more_array = yield(count).compact
  end

  def cache_and_set(key, &to_cache)
    data = cache("#{key}", {:expires_in => 1.day}, &to_cache)
    instance_variable_set(:"@#{key}", data) if data
  rescue
    logger.error "error caching key=#{key} (#{$!})"
    raise
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cite = @cites[rand(@cites.size)]
    more_stuff(@friends.size) do |count|
      @friends[0..count]
    end if @friends
  end

  def gallery
    more_stuff(@fotos.size) do |count|
      @fotos[0..count].each.map do |foto|
        (@picture_hash ||= {})[foto.album_id] = cache_and_set(:"gallery_images_#{foto.album_id}"){Helper::picasa_fotos(foto.pictures_url)}
        foto
      end
    end
  end

  def blog
    more_stuff(@posts.size) do |count|
      @posts[0..count]
    end
  end
end

app/controllers/interest_controller.rb
require 'vpim/vcard'

class InterestController < ApplicationController
  def index; end
  def curriculum; end
  def employer; end

  def vcard
    card = Vpim::Vcard::Maker.make2 do |maker|
      maker.name do |name|
        name.given = 'Klaus Peter'
        name.family = 'Schröder'
      end
      maker.add_addr do |addr|
        addr.street = 'Tigerstr. 32'
        addr.postalcode = '22525'
        addr.locality = 'Hamburg'
        addr.country = 'Deutschland'
      end
      maker.nickname = "phoet"
      maker.birthday = Date.new(1980, 8, 27)
      maker.add_photo { |photo| photo.link = 'http://www.gravatar.com/avatar/056c32203f8017f075ac060069823b66.png' }
      maker.add_email('ps@nofail.de')
    end

    send_data card.to_s, filename: 'peter_schroeder.vcf'
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  def index; end
  def github; end
  def bookshelf
    more_stuff(@books.size) do |count|
      asins = @books[0..count].map(&:asin)
      cache(:"books_#{asins.join}"){ @books[0..count] }
    end
  end
end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper
  def age
    birthday = Date.new(1980, 8, 27)
    age = Date.today.year - birthday.year
    age -= 1 if Date.today < birthday + age.years
    age
  end

  def names
    'Peter Schröder, Phoet, Señor Developer'
  end

  def keywords
    "#{names}, Ruby, Rails, Ruby on Rails, Software Development"
  end

  def website_url
    'www.phoet.de'
  end

  def menuitems
    Helper::menu.map{|m|m.subitems.map{|s|"#{m.id}/#{s.id}"}}.flatten
  end

  def app_info
    "<!-- Running on Rails #{Rails.version} and rendering took #{Time.new - @rendering_start} seconds -->".html_safe
  end

  def title(controller)
    Helper::menu.each do |m|
      cname = controller.controller_name
      m.subitems.each do |sub|
        aname = controller.action_name
        return "#{m.name} > #{sub.name}" if sub.id == aname
      end if m.id == cname
    end
  end

  def category_name(name)
    Helper::menu.find() do |m|
      m.id == name
    end.name
  end

  def menu(options={})
    top = options[:top].nil? || options[:top]
    current_controller = options[:controller] || controller.controller_name
    if top
      items = Helper::menu
    else
      items = Helper::menu.find() do |m|
        m.id == current_controller
      end.subitems
    end
    items.map do |i|
      page_options = (top ? {:controller => i.id} : {:controller => current_controller, :action => i.id})
      a = [current_controller, controller.action_name].include?(i.id)
      b = current_page?(page_options)
      cssclass = (a || b) ? ' class="current_page_item"' : ''
      link = link_to(i.name, page_options, {:title => i.name})
      "<li #{cssclass}>#{link}</li>\n"
    end.join.html_safe
  end

  def calc_difference(time_string)
    distance_of_time_in_words_to_now(time_string)
  end

  def links_4_twitter(text)
    ret = auto_link(text)
    regex = /(^|\s)#(\S+)/
    text.scan(regex) do |m|
      match = '#' + m[1]
      link = link_to match, "http://search.twitter.com/search?q=#{m[1]}"
      ret = ret.gsub(match, link)
    end
    text.scan(/@(\w+)/) do |m|
      match = '@' + m[0]
      link = link_to match, "http://twitter.com/#{m[0]}"
      ret = ret.gsub(match, link)
    end
    ret.html_safe
  end
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="/images/emoji/#{emoji.image_filename}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/helpers/interest_helper.rb
module InterestHelper
  def file_size file_name
    File.size(file_name) / 1000
  end
end

app/views/home/blog.html.haml
.post
	.post_body= render :partial=>"shared/quote", :locals=>{ :author =>'Kindermund', :text=>'Hallo liebes Tagebuch ...' }
	
	#blog
		- @more_array.each do |t|
			.post_title
				%h2
					%a{:href=>t.url, :title=>h(t.title)}=h(t.title)
			.post_date
				= "Erstellt am #{t.published} von "
				%a{:href=>t.author_url, :title=>t.author_name}=t.author_name
			.post_body= t.content
			%div &nbsp;
			.clearer &nbsp;
			.post_meta
				Tags:
				- if t.tags.nil?
					="-"
				- else
					- t.tags.each do |tag|
						%a{:href=>"http://uschisblogg.blogspot.com/search/label/#{tag}", :title=>"#{tag}"}= tag
				|
				- if t.comment_count == 0
					keine Kommentare
				- else
					%a{:href=>t.comment_link, :title=>"#{t.comment_count} Kommentare"}= "#{t.comment_count} Kommentare"
			%div &nbsp;
		
		= render :partial=>'shared/more', :locals=>{:name=>'Einträge'}

app/views/home/gallery.html.haml
.post
  .post_body= render :partial => "shared/quote", :locals => { :author =>'Werbebranche', :text => 'Ein Bild sagt mehr als tausend Worte.' }
  -unless @gallery_images.nil?
    %div
      .post_body
        -@gallery_images.each do |image|
          %a{:href => image.picture}
            %img{:src => image.thumbnail, :class => "alignleft"}
  .clearer &nbsp;
  #gallery
    -@more_array.each do |t|
      .gallery
        .post_title
          %a{:href=>t.url, :title=>t.title}
            %h2= t.title.truncate(18)
        .post_body.gallery-slideshow-container
          %a{:href=>t.url, :title=>t.title, :class=>'slideshow', :name=>t.album_id}
            %img{:src => t.thumbnail, :alt => t.title, :class => "alignleft", :style => "width:160px;height:160px;"}
            -@picture_hash[t.album_id][0..2].each do |f|
              %img{:src => f.thumbnail, :alt => f.title, :class => "alignleft mini"}
        .clearer &nbsp;
        .post_meta
          = link_to "#{t.photo_count} Fotos", t.url, :title => t.title
          = "vom #{t.published} von "
          = link_to t.author_name, t.author_url, :title => t.title
        %div &nbsp;
      %div{:class=>"images images_#{t.album_id}"}
        -@picture_hash[t.album_id].each do |image|
          %li
            %a{:href => image.picture}
              %img{:src => image.thumbnail}
    .clearer &nbsp;
    = render :partial => 'shared/more', :locals => {:name => 'Alben'}

app/views/home/index.html.haml
.post
  .post_body
    = render :partial=>"shared/quote", :locals=>{ :author=>@cite.author, :text=>@cite.text }
    %p
      Privates, Fachliches und Interessantes (oder so), auf jeden Fall gibt's hier:
    %ul
      %li
        Einträge aus meinem
        =link_to('Tagebuch', :action=>'blog')
      %li
        meine
        =link_to('Open Source Projekte', :controller=>'work', :action => "github")
      %li
        Zahlreiche Möglichkeiten mich zu
        =link_to('kontaktieren', :controller=>'interest')
      %li
        Meinen
        =link_to('Lebenslauf', :controller=>'interest', :action=>'curriculum')
      %li
        =link_to('Arbeitsproben', :controller=>'interest', :action=>'employer' )
        aus meinem beruflichen Werdegang

-if @more_array
  #index.post
    .post_title
      %h2
        %a{:href=>"http://twitter.com/phoet/friends", :title=>"Was geht auf Twitter?"} Was geht auf Twitter?
    .comment_list
      -@more_array.each do |friend|
        .comment.alt
          .comment_gravatar.left
            %img{:alt=>friend.name, :title=>friend.name, :src=>friend.profile_image_url, :height=>32, :width=>32}
          .comment_author.left
            %a{:href=>"http://twitter.com/#{friend.screen_name}"}="#{friend.name}, "
            %a{:href=>"http://twitter.com/#{friend.screen_name}/followers"}="#{friend.friends_count} Verfolger"
            .comment_date
              -if friend.status
                zuletzt Aktualisiert am
                =l(friend.status.created_at)
          .clearer &nbsp;
          .comment_body
            %p
              -if friend.status
                =links_4_twitter(h(friend.status.text))

    = render :partial=>'shared/more', :locals=>{:name=>'Tweets'}

app/views/interest/_curriculum_bullets.html.haml
.post
  .post_title
    %h1 in Stichpunkten
  .post_body
    %dl
      %dt Visitenkarte
      %dd
        Name:
        %strong Peter Schröder
      %dd
        Anschrift:
        %strong Tigerstr. 32, 22525 Hamburg
      %dd
        Geburtstag:
        %strong 27. August 1980
      %dd
        E-Mail:
        %strong ps@nofail.de

      %dt Ausbildung
      %dd Allgemeine Hochschulreife mit Vollabitur im Juli 2000
      %dd Diplom (FH) in Informatik im Juli 2005

      %dt Freiberuflich
      %dd Software-Entwickler bei der Qype GmbH, jetzt Yelp Inc.
      %dd Software-Entwickler bei der "Wer liefert Was?" GmbH in Hamburg
      %dd DevOps bei Shopify Inc. Remote in Hamburg
      %dd Software-Entwickler bei der Jimdo GmbH in Hamburg
      %dd Head of Backend-Engineering bei der Jimdo GmbH in Hamburg
      %dd Software-Entwickler bei der XING AG in Hamburg
      %dd Software-Entwickler bei der sum.cumo GmbH in Hamburg
      %dd CTO bei der Penseo GmbH in Hamburg

      %dt Festanstellung
      %dd Praktika als Software-Entwickler unter anderem bei der wquadrat GmbH in Kiel, der GfeH mbH in Hamburg und der Anybet GmbH in Hamburg
      %dd Entwickler für Online-Games bei der e-sport GmbH in Hamburg
      %dd Software-Entwickler bei der freenet.de AG in Hamburg
      %dd Software-Entwickler bei der blau Mobilfunk GmbH in Hamburg
      %dd Software-Entwickler bei Shopify Inc. in Ottawa, Kanada

      %dt Paradigma
      %dd Agile Software-Entwicklung und Design
      %dd Testgetriebene Entwicklung
      %dd Serviceorientierte Architektur

app/views/interest/_curriculum_table.html.haml
.post
  .post_title
    %h1 Tabellarisch
  .post_body
    %dl
      %dt Schule und Studium
      %dd
        %strong 1987-1991
        Grundschule Gettorf
      %dd
        %strong 1991-2000
        Gymnasium Kronshagen
      %dd
        %strong Juli 2000
        Allgemeine Hochschulreife (Abitur)
      %dd
        %strong 2000-2001
        Zivildienst am Studentenwerk S-H
      %dd
        %strong 2001-2005
        Studium der Medieninformatik FH-Flensburg
      %dd
        %strong Juli 2005
        Diplom Informatiker (FH)

      %dt Praktika
      %dd
        %strong Sommer 2003
        Praxissemester und befristete Tätigkeit als PHP-Entwickler bei der wquadrat Medien GmbH in Kiel
      %dd
        %strong 2004-2005
        Praxissemester und anschließende Diplomarbeit als Java-Entwickler bei der GfeH mbH in Hamburg
      %dd
        %strong Sommer 2006
        Praktikum als J2EE-Entwickler bei der ANYBET GmbH in Hamburg

      %dt Berufserfahrung
      %dd
        %strong Juli-Dezember 2005
        Projektarbeit mit Befristung als Java-Entwickler bei der wquadrat Medien GmbH in Kiel/Hamburg
      %dd
        %strong Januar-Mai 2006
        Projektarbeit als PHP-Entwickler für Browsergames bei der e-sport GmbH (Bigpoint GmbH) in Hamburg
      %dd
        %strong 2006-2007
        Java-Web-Entwickler bei der Freenet.de AG
      %dd
        %strong 2007-2010
        J2EE-Entwickler bei der blau Mobilfunk GmbH
      %dd
        %strong September 2010
        Rails-Entwickler bei der tolingo GmbH
      %dd
        %strong Oktober-November 2010
        Ruby Entwickler bei der Verkehrsmittelvergleich.de GmbH
      %dd
        %strong Januar 2014 bis Januar 2015
        Ruby Entwickler, DevOps bei Shopify Inc.

      %dt Projekte
      %dd
        %strong Februar-Mai 2011
        Weiterentwicklung und Optimierung der Rails-Plattform bei Qype.com
      %dd
        %strong Juni 2011
        Unterstützung bei der Migration zu Grails bei DatingCafe.de
      %dd
        %strong September 2011 bis Mai 2013
        Neuentwicklung der Plattform mit Rails bei WLW.de
      %dd
        %strong Feburar 2015 bis Oktober 2016
        Unterstützung bei der Implementierung einer service-orientierten Architektur bei der Jimdo GmbH
      %dd
        %strong Dezember 2016 bis Februar 2017
        Neuentwicklung eines Notification-Centers auf Basis von Ruby on Rails bei der XING AG
      %dd
        %strong Januar 2018 bis April 2018
        Entwicklung der Verwaltungs-Backends für Dextra und Nexible bei sum.cumo
      %dd
        %strong März 2017 bis dato
        Unternehmer, Mitgründer, Interims-CTO bei der Penseo GmbH in Hamburg

app/views/interest/curriculum.html.haml
.post
  .post_body= render :partial => "shared/quote", :locals => { :author =>'Wilhelm Busch', :text => 'Ist der Ruf erst ruiniert, lebt es sich ganz ungeniert.' }

=render :partial => 'curriculum_bullets'
=render :partial => 'curriculum_table'

app/views/interest/index.html.haml
.post
  .post_body
    = render :partial => "shared/quote", :locals => { :author =>'Peter Schröder', :text => 'Ich bin nicht neugierig, ich will nur alles wissen!' }

    %span(style="float:right;font-size:smaller;")= link_to "⬇︎ vCard", vcard_url
    %h3
      So bin ich zu erreichen:

    %dl
      %dt Anschrift
      %dd Tigerstr. 32, 22525 Hamburg

      %dt E-Mail
      %dd
        %strong
          = mail_to "ps@nofail.de"

      %dt Social-Media
      %dd= link_to "Twitter", "http://twitter.com/phoet", :title => "Twitter"
      %dd= link_to "GitHub", "http://github.com/phoet", :title => "GitHub"

app/views/layouts/application.html.haml
!!! XML
!!!
%html{:xmlns=>"http://www.w3.org/1999/xhtml", :lang => "de"}
  %head
    %meta{'http-equiv'=>"content-type", :content=>"text/html; charset=UTF-8"}
    %meta{:name=>"language", :content=>"deutsch, de"}
    %meta{:name=>"description", :content=>keywords}
    %meta{:name=>"keywords", :content=>keywords}
    %meta{:name=>"author", :content=>names}
    %meta{:name=>"robots", :content=>"index,follow"}
    %meta{:name=>"verify-v1", :content=>"DYzuVUS2Ez7zNwT2DNuxbAh2jdIF61Ro0/ft212nZpI="}
    %meta{:name=>"google-site-verification", :content=>"9ROlZo5P92RwF8jhAFrCrFKdwYe15GdN39wO2SRKO7U"}

    %link{:rel=>"shortcut icon", :href=>"/favicon.png", :type=>"image/png"}
    %link{:rel=>"icon", :href=>"/favicon.png", :type=>"image/png"}
    %link{:rel=>"me", :href=>"https://ruby.social/@phoet"}

    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %title="#{title(controller)} - Peter Schröder - Phoet - #{keywords}"

  %body#top
    #layout_wrapper_outer
      #layout_wrapper
        #layout_top
          #site_title
            %h1
              %a{:href=>"/", :title=>"Peter Schröder"}
                Peter
                %span Schröder
            %h2 Phoet, Señor Developer

        #layout_body_outer
          #layout_body
            #navigation
              #nav1
                %ul=menu()
                .clearer &nbsp;
              #nav2
                %ul=menu(:top=>false)
                .clearer &nbsp;

            #main
              #content_outer.left
                #content= yield

              #sidebar_outer.right
                #sidebar
                  = render 'teaser/about'
                  = render 'teaser/blog',         posts: @posts   if @teaser.include? :blog
                  = render 'teaser/bookshelf',    books: @books   if @teaser.include? :bookshelf
                  = render 'teaser/twitter',      tweets: @tweets if @teaser.include? :twitter
                  = render 'teaser/github_repos', repos: @repos   if @teaser.include? :repos
                  = render 'teaser/github_gists', gists: @gists   if @teaser.include? :gists
              .clearer &nbsp;

            #dashboard
              #dashboard_inner
                .col3.left
                  .col3_content
                    .col_title=category_name('home')
                    %ul=menu(:controller=>'home', :top=>false)

                .col3mid.left
                  .col3_content
                    .col_title=category_name('work')
                    %ul=menu(:controller=>'work', :top=>false)

                .col3.right
                  .col3_content
                    .col_title=category_name('interest')
                    %ul=menu(:controller=>'interest', :top=>false)

                .clearer &nbsp;

        #footer
          .left
            &copy;
            &reg;
            =Time.new.year
            %a{:href=>"http://#{website_url}", :title=>"phoet"}=website_url
            see some code on
            %a{:href=>"http://github.com/phoet/basement/", :title=>"github phoet"} github
          .right
            %a{:href=>"http://templates.arcsin.se/", :title=>'Arcsin-Templates'} Website template
            by
            %a{:href=>"http://arcsin.se/",:title=>'Arcsin'} Arcsin
    = render '/shared/javascript'
= app_info

app/views/layouts/default.html.haml
!!! XML
!!!
%html{:xmlns=>"http://www.w3.org/1999/xhtml"}
  %head
    %meta{'http-equiv'=>"content-type", :content=>"text/html; charset=UTF-8"}
    %meta{'http-equiv'=>"content-language", :content=>"de"}
    %meta{'http-equiv'=>"language", :content=>"de"}
    %meta{:name=>"language", :content=>"deutsch, de"}
    %meta{:name=>"description", :content=>"#{names},#{keywords}"}
    %meta{:name=>"keywords", :content=>"#{names},#{keywords}"}
    %meta{:name=>"author", :content=>names}
    %meta{:name=>"robots", :content=>"index,follow"}
    %meta{:name=>"verify-v1", :content=>"DYzuVUS2Ez7zNwT2DNuxbAh2jdIF61Ro0/ft212nZpI="}
    
    %link{:rel=>"shortcut icon", :href=>"/favicon.png", :type=>"image/png"}
    %link{:rel=>"icon", :href=>"/favicon.png", :type=>"image/png"}
    
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js', 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js', 'jquery.lightbox-0.5', 'application'
    = stylesheet_link_tag 'jquery.lightbox-0.5', 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css', 'style'

    %title="#{title(controller)} - Peter Schröder - Phoet - #{keywords}"

  %body#top
    #layout_wrapper_outer
      #layout_wrapper
        #layout_top
          #site_title
            %h1
              %a{:href=>"/", :title=>"Peter Schröder"}
                Peter 
                %span Schröder
            %h2= keywords
        
        #layout_body_outer
          #layout_body
            #navigation
              #nav1
                %ul=menu()
                .clearer &nbsp;
              #nav2
                %ul=menu(:top=>false)
                .clearer &nbsp;
            
            #main
              #content_outer.left
                #content= yield
          
              #sidebar_outer.right
                #sidebar
                  = render :partial => 'teaser/about'
                  = render :partial => 'teaser/blog', :locals => {:posts => @posts} if @teaser.include? :blog
                  = render :partial => 'teaser/bookshelf', :locals => {:books => @books} if @teaser.include? :bookshelf
                  = render :partial => 'teaser/gallery', :locals => {:images => @random_gallary_images} if @teaser.include? :gallery
                  = render :partial => 'teaser/twitter', :locals => {:tweets => @tweets} if @teaser.include? :twitter
                  = render :partial => 'teaser/github_repos', :locals => {:repos => @repos} if @teaser.include? :repos
                  = render :partial => 'teaser/github_gists', :locals => {:gists => @gists} if @teaser.include? :gists
              .clearer &nbsp;
        
            #dashboard
              #dashboard_inner
                .col3.left
                  .col3_content
                    .col_title=category_name('home')
                    %ul=menu(:controller=>'home', :top=>false)
                
                .col3mid.left
                  .col3_content
                    .col_title=category_name('work')
                    %ul=menu(:controller=>'work', :top=>false)
                
                .col3.right
                  .col3_content
                    .col_title=category_name('interest')
                    %ul=menu(:controller=>'interest', :top=>false)
            
                .clearer &nbsp;
    
        #footer
          .left
            &copy; 
            =Time.new.year
            %a{:href=>"http://#{website_url}", :title=>"phoet"}=website_url
            &reg;
            %a{:href=>"http://www.peter-schröder.info", :title=>"peter schröder"} www.peter-schröder.info
            see some code on 
            %a{:href=>"http://github.com/phoet/basement/", :title=>"github phoet"} github
            or recommend me on
            %a{:href => "http://www.workingwithrails.com/recommendation/new/person/17645-peter-schr-der"} Working With Rails
          .right
            %a{:href=>"http://templates.arcsin.se/", :title=>'Arcsin-Templates'} Website template
            by
            %a{:href=>"http://arcsin.se/",:title=>'Arcsin'} Arcsin
          .clearer &nbsp;
          .left
            Running on 
            %a{:href=>"http://www.rubyonrails.org", :title=>"Ruby on Rails"}="Rails 3.0.0.beta"
            =" and rendering took #{Time.new - @rendering_start} seconds"
          .clearer &nbsp;
          =render :partial => '/shared/seitwert'


    %script{:type=>"text/javascript"}
      var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
      document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

    %script{:type=>"text/javascript"}
      try {
      var pageTracker = _gat._getTracker("UA-2711231-1");
      pageTracker._trackPageview();
      } catch(err) {}

app/views/shared/_javascript.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2711231-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_more.html.haml
.post_meta.more=link_to("&#187; Mehr #{name} &#171;".html_safe, {:action=>action_name,:id=>session[action_name] + 2}, {:title=>name, :name=>action_name})

app/views/shared/_quote.html.haml
%blockquote>
	%p= text
	%p
		%cite= "- #{author}"

app/views/teaser/_about.html.haml
.box#about
  .box_title= link_to('Über Mich', {:controller=>'interest', :action=>'curriculum'}, {:title=>'Über Mich'})
  .box_content
    .thumbnails
      = link_to({:controller=>'interest', :action=>'curriculum'}, {:class=>'thumb'}) do
        %img{:src=>"http://www.gravatar.com/avatar/056c32203f8017f075ac060069823b66.png", :alt=>"Peter Schröder", :title=>"Peter Schröder"}
      %p
        Ich bin
        = age
        Jahre alt, lebe in Cosa bei Friedland in Mecklenburg Vorpommern und
        betreibe dort mit meiner Frau Petra den
        = link_to("Naturcampingplatz Star Camp Cosa", "https://www.star-camp-cosa.de", :title => "Naturcampingplatz mit Ferienwohnungen Star Camp Cosa", :target => '_blank')

app/views/teaser/_blog.html.haml
.box
  .box_title=link_to('Tagebuch', {:controller=>'home', :action=>'blog'}, {:title=>'Tagebuch'})
  .box_content
    -if posts
      %ul
        -posts[0..4].each() do |post|
          %li
            %a{:href=>post.url, :title=>h(post.title)}=h(post.title).truncate(30)